---
- hosts: managementsrv
  name: Management server configuration
  become: true
  gather_facts: true
  tasks:
  - name: Install python 
    raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)   
  vars_files:
  - ./projvars.yml
  - ./preppackage.yml
  - ./provisionvars.yml
  roles:
  - { role: tools}
  - { role: redis, when: 'sensu_server'}
  - { role: sensu, when: 'sensu_server'}
  - { role: uchiwa, when: 'sensu_server'}
  - { role: influxdb, when: 'sensu_server'}
  - { role: ansible-elk, when: 'elk_server'}

- hosts: webservers
  name: Nodes configuration
  user: ubuntu
  become: true
  gather_facts: true
  tasks:
  - name: Install python 
    raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)
  vars_files:
  - ./projvars.yml
  - ./preppackage.yml
  - ./provisionvars.yml
  roles:
  - { role: tools}
  - { role: sensu-client, when: 'sensu_client'}
  - { role: prerequisites}
  - { role: provision}
